language: php

php:
    - 5.4
    - 5.5
    - 5.6

env:
    - SYMFONY_VERSION="~2.3.0"
    - SYMFONY_VERSION="~2.4.0"
    - SYMFONY_VERSION="~2.5.0"

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar require --no-update symfony/symfony:${SYMFONY_VERSION}
    - php composer.phar install --prefer-source

script: ./vendor/bin/phpunit --coverage-text
