sudo: false

language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    - COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION="^2.8.2"
    - SYMFONY_VERSION="^2.8.2" COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION="^3.0.0"
    - SYMFONY_VERSION="^3.0.0" COMPOSER_FLAGS="--prefer-lowest"

matrix:
    fast_finish: true

    allow_failures:
        - php: hhvm
        - env: SYMFONY_VERSION="dev-master"
    exclude:
        # Symfony 3.x requires PHP 5.5
        - php: 5.4
          env: SYMFONY_VERSION="~3.0.0"
        - php: 5.4
          env: SYMFONY_VERSION="dev-master"

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-source

script:
    - vendor/bin/phpunit --colors
